### ISSUE TITLE
WebSocket or Socket.io??

### ISSUE THREAD

**Issue by truptiQL** [au-ql/CORD-web-messenger#7]

**Comment by truptiQL** [comment]
Socket.IO provides features such as auto-reconnect, rooms, and fallback to long polling

**Comment by Hladdha** [comment]
Socket.IO is a library that provides an abstraction layer on top of WebSockets, making it easier to create realtime applications.

**Comment by Hladdha** [comment]
WebSockets provide more flexibility - you can design your own architecture and your own protocol on top (although this is incredibly difficult and time-consuming). In contrast, Socket.IO comes with a pre-designed architecture and protocol, which may become restrictive at some point.

**Comment by Hladdha** [comment]
for our use case socket.io would be great

**Comment by Hladdha** [comment]
Socket.IO provides a configurable Ping/Pong heartbeat mechanism, allowing you to detect if a connection is alive or not. Additionally, if and when a client gets disconnected, it automatically reconnects.
